version: "3"

services:
    streamlit_spcs:
        platform: linux/amd64
        build: .
        environment:        
            - SNOWFLAKE_ACCOUNT=
            - SNOWFLAKE_USER=
            - SNOWFLAKE_PASSWORD=
            - SNOWFLAKE_WAREHOUSE=AWH_XSMALL
            - SNOWFLAKE_DATABASE=SPCS_PLAYGROUND
            - SNOWFLAKE_SCHEMA=PUBLIC
            - SNOWFLAKE_ROLE=SPCS_SERVICE_ROLE
            - service_name=MyEnvVariablePlaceholder
        ports:
            - 8501:8501